[build.env]
passthrough = ["CFLAGS"]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/rust-cross/manylinux2014-cross:aarch64"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/rust-cross/manylinux2014-cross:x86_64"
